### ISSUE TITLE
issue_types not defined in json output.

### ISSUE THREAD

**Issue by rhenwood-arm** [arm-hpc/porting-advisor#5]
I've got porting-advisor installed from a clone of Master. It seems there is a problem with JSON output:

```
root@caefda440af3:/tmp/porting-advisor# porting-advisor --output-format csv ./ 
| Elapsed Time: 0:00:00                                                                                                                                                                               
filename,function,line,issue_type,description
root@caefda440af3:/tmp/porting-advisor# porting-advisor --output-format json ./
| Elapsed Time: 0:00:00                                                                                                                             
Traceback (most recent call last):
  File "/usr/local/bin/porting-advisor", line 11, in <module>
    load_entry_point('porting-advisor==1.4', 'console_scripts', 'porting-advisor')()
  File "/usr/local/lib/python3.8/dist-packages/porting_advisor-1.4-py3.8.egg/advisor/__init__.py", line 27, in main
    real_main()
  File "/usr/local/lib/python3.8/dist-packages/porting_advisor-1.4-py3.8.egg/advisor/main.py", line 152, in main
    report.write(sys.stdout, report_errors=not args.quiet)
  File "/usr/local/lib/python3.8/dist-packages/porting_advisor-1.4-py3.8.egg/advisor/report.py", line 71, in write
    self.write_items(output_file, sorted_items)
  File "/usr/local/lib/python3.8/dist-packages/porting_advisor-1.4-py3.8.egg/advisor/json_report.py", line 26, in write_items
    self.issue_types = issue_types
NameError: name 'issue_types' is not defined
```

**Comment by arm-chrjan01** [comment]
Thank you for the report Richard. I'll get that fixed ASAP.
